### PR TITLE
Add toast notification when a user/student is added

### LINKED ISSUE #101: Add toast notification or something similar when a user/student is added
https://getbootstrap.com/docs/5.0/components/toasts/

### PR DESCRIPTION
**Pull request by h3vanth**
resolves #101

### CODE REVIEW

**Comment by h3vanth** [comment]
> Thank you for the PR. It works well when adding a new user. Can you just put it above instead of having it at the bottom? toast-when-user-added
image
@Bam92 Please see if this ok. And also let me know if you want the message to disappear after few seconds.

**Comment by Bam92** [comment]
Yes, it's what I wanted just to let you know, the message should disappear after a while.

**Comment by Bam92** [comment]
Let me know when you're done so that I can merge the PR.

**Comment by h3vanth** [comment]
> Let me know when you're done so that I can merge the PR.

Pushed changes. Please check.

**Pull request merged**
